#!/ether/qktools/mksh
echo ''
echo 'BUILD STAGE II TOOLCHAIN'
echo ''
echo 'INSTALLING BINUTILS STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
export PATH=$PATH:/ether/qktmp/bin
echo 'START: configure --prefix=/usr --disable-werror --host=armv7l-nexos-linux-gnueabihf'  
cd /ether/build/binutils
if [!`/ether/src/binutils-2.24/configure --prefix=/usr --disable-werror --host=armv7l-nexos-linux-gnueabihf`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-------------------------------------'
echo 'FINISHED INSTALLING BINUTILS STAGE II'
echo `date`
echo '-------------------------------------'
fi
echo 'INSTALLING GCC STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
echo 'START: configure --prefix=/usr --host=armv7l-nexos-linux-gnueabihf --enable-languages="c,c++" --enable-shared --disable-static --disable-bootstrap --disable-multilib' 
cd /ether/build/gcc
if [!`/ether/src/gcc-4.9.2/configure --prefix=/usr --host=armv7l-nexos-linux-gnueabihf --enable-languages="c,c++" --enable-shared --disable-static --disable-bootstrap --disable-multilib`]; 
then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
sed -i 's/none-/armv7l-/' Makefile
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit` ]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
#exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '--------------------------------'
echo 'FINISHED INSTALLING GCC STAGE II'
echo `date`
echo '--------------------------------'
fi
echo 'INSTALLING LINUX HEADERS STAGE I'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
cd /ether/src/linux-3.1.10
echo 'START: make mrproper' 
if [!`make mrproper`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make INSTALL_HDR_PATH=/ether/qkbit/usr headers_install` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make mrproper` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '------------------------------------------'
echo 'FINISHED INSTALLING LINUX HEADERS STAGE II'
echo `date`
echo '------------------------------------------'
fi
echo 'INSTALLING GLIBC STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
echo 'START: configure --prefix=/usr' 
cd /ether/build/glibc
if [!`/ether/src/glibc-2.20/configure --prefix=/usr`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit 
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit 
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit`]; then
echo 'INSTALL FAILED'
echo `date`
exit 
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit 
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '--------------------------------------'
echo 'FINISHED INSTALLING GLIBC STAGE II'
echo `date`
echo '--------------------------------------'
fi
echo 'POST-PROCESSING THE ENVIRONMENT'
echo 'SYSTEM READY'

