#!/ether/qktools/mksh
echo ''
echo 'BUILD STAGE II TOOLCHAIN'
echo ''
echo 'INSTALLING BINUTILS STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
export PATH=$PATH:/ether/qktmp/bin
echo 'START: configure --prefix=/usr --disable-werror --host=i386-qkbit-linux'  
cd /ether/build/binutils
if [!`/ether/src/binutils-2.24/configure --prefix=/usr --disable-werror --host=i386-qkbit-linux`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-------------------------------------'
echo 'FINISHED INSTALLING BINUTILS STAGE II'
echo `date`
echo '-------------------------------------'
fi
echo 'INSTALLING COMPILER SUITE STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
cd /ether/build/llvm
echo 'START: configure' 
if [!``]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-------------------------------------------'
echo 'FINISHED INSTALLING COMPILER SUITE STAGE II'
echo `date`
echo '-------------------------------------------'
fi
echo 'INSTALLING LINUX HEADERS STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
cd /ether/src/linux-3.1.10
echo 'START: make mrproper' 
if [!`make mrproper`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make INSTALL_HDR_PATH=/ether/qkbit/usr headers_install` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make mrproper` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '------------------------------------------'
echo 'FINISHED INSTALLING LINUX HEADERS STAGE II'
echo `date`
echo '------------------------------------------'
fi
echo 'INSTALLING LIBC STAGE II'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
echo 'START: configure --prefix=/ether/qktmp --host=i386-qkbit-linux --enable-static --enable-shared --syslibdir=/lib --includedir=/usr/include' 
cd /ether/src/musl-1.1.6
if [!`./configure --prefix=/ether/qktmp --host=i386-qkbit-linux --enable-static --enable-shared --syslibdir=/lib --includedir=/usr/include`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install DESTDIR=/ether/qkbit`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-------------------------------------'
echo 'FINISHED INSTALLING LIBC STAGE II'
echo `date`
echo '-------------------------------------'
fi
echo 'POST-PROCESSING THE ENVIRONMENT'
echo 'SYSTEM READY'

