#!/ether/qktools/mksh
echo ''
echo 'START SECURE UNPACK'
echo ''
sleep 3
echo 'Verify binutils...'
echo `cat /ether/src/compressed/binutils.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/binutils.7z`
echo ''
sleep 2
echo 'Verify gcc...'
echo `cat /ether/src/compressed/gcc.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/gcc.7z`
echo ''
sleep 2
echo 'Verify linux...'
echo `cat /ether/src/compressed/linux.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/linux.7z`
echo ''
sleep 2
echo 'Verify libc...'
echo `cat /ether/src/compressed/musl.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/musl.7z`
echo ''
sleep 2
echo 'Verify gmp...'
echo `cat /ether/src/compressed/gmp.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/gmp.7z`
echo ''
sleep 2
echo 'Verify mpfr...'
echo `cat /ether/src/compressed/mpfr.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/mpfr.7z`
echo ''
sleep 2
echo 'Verify mpc...'
echo `cat /ether/src/compressed/mpc.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/mpc.7z`
echo ''
sleep 2
echo 'PLEASE VERIFY ALL CHECKSUMS'
echo 'DO NOT CONTINUE IF THERE IS A MISMATCH!'
sleep 10
export PATH=$PATH:/ether/qktools
echo ''
echo 'Extract binutils'
mkdir -p /ether/src/binutils-2.24
cd /ether/src/binutils-2.24
if [! `7zaqk x ../compressed/binutils.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract gcc'
mkdir -p /ether/src/gcc-4.9.2
cd /ether/src/gcc-4.9.2
if [! `7zaqk x ../compressed/gcc.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo ''
echo 'Extract linux'
mkdir -p /ether/src/linux-3.1.10
cd /ether/src/linux-3.1.10
if [! `7zaqk x ../compressed/linux.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract libc'
mkdir -p /ether/src/musl-1.1.6
cd /ether/src/musl-1.1.6
if [! `7zaqk x ../compressed/musl.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract gmp'
mkdir -p /ether/src/gmp-6.0.0a
cd /ether/src/gmp-6.0.0a
if [! `7zaqk x ../compressed/gmp.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract mpfr'
mkdir -p /ether/src/mpfr-3.1.2
cd /ether/src/mpfr-3.1.2
if [! `7zaqk x ../compressed/mpfr.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract mpc'
mkdir -p /ether/src/mpc-1.0.2
cd /ether/src/mpc-1.0.2
if [! `7zaqk x ../compressed/mpc.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo ''
sleep 3
echo 'Try "./qktools/02_qktmp" if this script was successful.'
echo 'SYSTEM READY'
