#!/ether/qktools/mksh
echo ''
echo 'START SECURE UNPACK'
echo ''
sleep 3
echo 'Verify binutils...'
echo `cat /ether/src/compressed/binutils.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/binutils.7z`
echo ''
sleep 2
echo 'Verify llvm...'
echo `cat /ether/src/compressed/llvm.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/llvm.7z`
echo ''
sleep 2
echo 'Verify linux...'
echo `cat /ether/src/compressed/linux.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/linux.7z`
echo ''
sleep 2
echo 'Verify libc...'
echo `cat /ether/src/compressed/musl.7z.sha1`
echo ''
echo `sha1sum /ether/src/compressed/musl.7z`
echo ''
sleep 2
echo 'PLEASE VERIFY ALL CHECKSUMS'
echo 'DO NOT CONTINUE IF THERE IS A MISMATCH!'
sleep 10
export PATH=$PATH:/ether/qktools
echo ''
echo 'Extract binutils'
mkdir -p /ether/src/binutils-2.24
cd /ether/src/binutils-2.24
if [! `7zaqk x ../compressed/binutils.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract llvm'
mkdir -p /ether/src/llvm
cd /ether/src/llvm
if [! `7zaqk x ../compressed/llvm.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo ''
echo 'Extract linux'
mkdir -p /ether/src/linux-3.1.10
cd /ether/src/linux-3.1.10
if [! `7zaqk x ../compressed/linux.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo '' 
echo 'Extract libc'
mkdir -p /ether/src/musl-1.1.6
cd /ether/src/musl-1.1.6
if [! `7zaqk x ../compressed/musl.7z` ]; then
	echo 'SECURE UNPACK FAILED'
else
	echo 'SECURE UNPACK SUCCESSFUL'
fi
echo ''
sleep 3
echo 'Try "./qktools/02_qktmp" if this script was successful.'
echo 'SYSTEM READY'
