#!/ether/qktools/mksh
echo ''
echo 'BUILD THE STAGE I TOOLCHAIN'
echo ''
sleep 3
echo 'INSTALLING BINUTILS STAGE I'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
export PATH=$PATH:/ether/qktmp/bin
echo 'START: configure --prefix=/ether/qktmp --with-sysroot=/ether/qktmp --disable-werror --target=i386-qkbit-linux --with-lib-path=/ether/qktmp/lib' 
cd /ether/build/binutils
if [!`/ether/src/binutils-2.24/configure --prefix=/ether/qktmp --with-sysroot=/ether/qktmp --disable-werror --target=i386-qkbit-linux --with-lib-path=/ether/qktmp/lib`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '------------------------------------'
echo 'FINISHED INSTALLING BINUTILS STAGE I'
echo `date`
echo '------------------------------------'
fi
echo 'INSTALLING COMPILER SUITE STAGE I'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
cd /ether/build/llvm
echo 'START: configure' 
if [!``]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '------------------------------------------'
echo 'FINISHED INSTALLING COMPILER SUITE STAGE I'
echo `date`
echo '------------------------------------------'
fi
echo 'INSTALLING LINUX HEADERS STAGE I'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
cd /ether/src/
echo 'START: make mrproper' 
if [!`make mrproper`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make INSTALL_HDR_PATH=/ether/qktmp headers_install` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make mrproper` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-----------------------------------------'
echo 'FINISHED INSTALLING LINUX HEADERS STAGE I'
echo `date`
echo '-----------------------------------------'
fi
echo 'INSTALLING LIBC STAGE I'
echo '3...'
sleep 1
echo '2...'
sleep 1
echo '1...'
sleep 1
echo 'START: configure --prefix=/ether/qktmp --target=i386-qkbit-linux --enable-static --enable-shared --syslibdir=/ether/qktmp/lib --includedir=/ether/qktmp/usr/include' 
cd /ether/src/musl-1.1.6
if [!`./configure --prefix=/ether/qktmp --target=i386-qkbit-linux --enable-static --enable-shared --syslibdir=/ether/qktmp/lib --includedir=/ether/qktmp/usr/include`]; then
echo 'CONFIGURE FAILED'
echo `date`
exit
else 
echo 'CONFIGURE SUCCESSFUL'
echo 'STARTING BUILD'
sleep 3
fi
if [ ! `make` ]; then
echo 'BUILD FAILED'
echo `date`
exit
else
echo 'BUILD SUCCESSFUL'
echo 'STARTING INSTALL'
sleep 3
fi
if [ ! `make install`]; then
echo 'INSTALL FAILED'
echo `date`
exit
else
echo 'INSTALL SUCCESSFUL'
echo 'STARTING CLEAN'
sleep 3
fi
if [ ! `make clean` ]; then
echo 'CLEAN FAILED'
echo `date`
exit
else
echo 'CLEAN SUCCESSFUL'
sleep 3
echo '-------------------------------------'
echo 'FINISHED INSTALLING LIBC STAGE I'
echo `date`
echo '-------------------------------------'
fi
echo ''
sleep 3
echo 'SYSTEM READY'
echo `date`
