#!/ether/qktools/mksh
rm -rf /ether/build/llvm/*
rm -rf /ether/build/binutils/*
cd /ether/src/linux-
make mrproper
rm -rf /ether/src/toybox-0.5.1/*
cd /ether/src/zlib-1.2.8
make distclean
rm -rf /ether/build/nano/*
rm -rf /ether/build/ncurses/*
cd /ether/src/musl-1.1.6
make distclean
echo 'SYSTEM READY'
