#!/ether/qktools/mksh
rm -rf /ether/build/gcc/*
rm -rf /ether/build/binutils/*
cd /ether/src/linux-3.1.10
make mrproper
rm -rf /ether/src/toybox-0.5.1/*
rm -rf /ether/build/classpath/*
rm -rf /ether/build/jamvm/*
cd /ether/src/zlib-1.2.8
make distclean
rm -rf /ether/build/nano/*
rm -rf /ether/build/ncurses/*
cd /ether/src/musl-1.1.6
make distclean
echo 'SYSTEM READY'
