#!/ether/qktools/mksh
rm -rf /ether/src/llvm
rm -rf /ether/src/binutils-2.24
rm -rf /ether/src/musl-1.1.5
rm -rf /ether/src/linux-3.1.10
rm -rf /ether/src/toybox-0.5.1
rm -rf /ether/src/zlib-1.2.8
rm -rf /ether/src/nano-2.2.6
rm -rf /ether/src/ncurses-5.9
rm -rf /ether/src/musl-1.1.6
echo 'SYSTEM READY'
